[package]
name = "sc-owner"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
shared = { path = "../shared" }
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
hex = { version = "0.4", default-features = false, features = ["alloc"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
