[package]
name = "methods"
version = "0.1.0"
edition = "2021"
license = "MIT"

[build-dependencies]
risc0-build = { version = "2.0.0" }
risc0-build-ethereum = { version = "2.0.0" }

[package.metadata.risc0]
methods = ["guest"]
