[package]
name = "shared"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
hex = { version = "0.4", default-features = false, features = [ "alloc", "std" ]  }
evm = { version = "0.42.0", default-features = false, features = ["with-serde"] }
primitive-types =  { version = "0.12.0", default-features = false }
ethereum-types = { version = "0.14.1", default-features = false  }
sha3 = { version = "0.10.6", default-features = false  }
clap = { version = "4.0", features = ["derive"] } 
hex-literal = { version = "0.3.4", default-features = false  }
tiny-keccak = { version = "2.0", features = ["keccak"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
sha2 = { version = "0.10.6" }
hpke = { version = "0.12.0" }
tracing = { version = "0.1" }
risc0-zkvm = { version = "2.0.0" }
anyhow = "1.0"